---
- name: install support tools
  yum: name={{ item }} state=present
  with_items: [ git, wget ]

- name: run composer-install script
  script: creates="/usr/sbin/composer" files/composer-install.sh

- name: create drush home
  file: path=/opt/drush state=directory

- name: fetch drush from git
  git: repo="https://github.com/drush-ops/drush.git" dest="/opt/drush" version="8.1.3"

- name: install drush via composer
  command: chdir="/opt/drush" composer install --no-plugins --no-scripts -d /opt/drush/

- name: create drush link
  file: src=/opt/drush/drush dest=/usr/bin/drush state=link

- name: detect edw user
  stat: path="/home/edw"
  register:
    edw_user_exists

- name: create ~/.drush directory
  file: path="/home/edw/.drush" state="directory" owner="php" group="users"
  when: (edw_user_exists.stat.exists == True)

- name: setup drushrc.php in home directory
  copy: src="roles/common/files/drushrc.php" dest="/home/edw/.drush/drushrc.php" owner="php" group="users"
  when: (edw_user_exists.stat.exists == True)
